local_pubs: [/Inertial/gps/fix, /Inertial/imu/data, /Inertial/gps/vel, /can_frame, /imu_torso/xsens/data,/garmin/fix]
foreign_pubs: [/axis_front/camera_info, /axis_front/image/compressed, /axis_rear/camera_info,  /axis_rear/image/compressed, /axis_left/camera_info, /axis_left/image/compressed, /axis_right/camera_info, /axis_right/image/compressed]
